import type { Product, Order, Address } from "@/types"

// Mock products data
export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Classic Aviator",
    description: "Timeless aviator sunglasses with premium metal frame and UV protection",
    price: 129.99,
    originalPrice: 179.99,
    images: ["/aviator-sunglasses-front-view.jpg", "/aviator-sunglasses-side-view.jpg"],
    category: "sunglasses",
    brand: "VisionPro",
    frameType: "aviator",
    material: "Metal",
    color: "Gold",
    lensType: "Polarized",
    inStock: true,
    rating: 4.5,
    reviewCount: 128,
    features: ["UV400 Protection", "Polarized Lenses", "Lightweight Frame", "Adjustable Nose Pads"],
  },
  {
    id: "2",
    name: "Modern Wayfarer",
    description: "Contemporary wayfarer design with acetate frame for everyday style",
    price: 99.99,
    images: ["/wayfarer-sunglasses-black.jpg", "/wayfarer-sunglasses-angle-view.jpg"],
    category: "sunglasses",
    brand: "UrbanEye",
    frameType: "wayfarer",
    material: "Acetate",
    color: "Black",
    lensType: "Standard",
    inStock: true,
    rating: 4.7,
    reviewCount: 256,
    features: ["Classic Design", "Durable Acetate", "UV Protection", "Comfortable Fit"],
  },
  {
    id: "3",
    name: "Round Vintage",
    description: "Retro-inspired round frames perfect for a vintage aesthetic",
    price: 89.99,
    images: ["/round-vintage-eyeglasses.jpg", "/round-glasses-side-view.jpg"],
    category: "eyeglasses",
    brand: "RetroVision",
    frameType: "round",
    material: "Metal",
    color: "Silver",
    inStock: true,
    rating: 4.3,
    reviewCount: 89,
    features: ["Vintage Style", "Lightweight", "Spring Hinges", "Prescription Ready"],
  },
  {
    id: "4",
    name: "Sport Performance",
    description: "High-performance sports sunglasses with wraparound design",
    price: 149.99,
    images: ["/sport-sunglasses-wraparound.jpg", "/athletic-sunglasses.jpg"],
    category: "sports",
    brand: "ActiveVision",
    frameType: "full-rim",
    material: "TR90",
    color: "Black/Red",
    lensType: "Polarized",
    inStock: true,
    rating: 4.8,
    reviewCount: 342,
    features: ["Impact Resistant", "Anti-Slip", "Polarized", "Lightweight TR90"],
  },
  {
    id: "5",
    name: "Cat-Eye Chic",
    description: "Elegant cat-eye frames for a sophisticated look",
    price: 119.99,
    images: ["/cat-eye-glasses-elegant.jpg", "/cat-eye-frames-side.jpg"],
    category: "eyeglasses",
    brand: "ChicVision",
    frameType: "cat-eye",
    material: "Acetate",
    color: "Tortoise",
    inStock: true,
    rating: 4.6,
    reviewCount: 167,
    features: ["Elegant Design", "Premium Acetate", "Comfortable", "Prescription Ready"],
  },
  {
    id: "6",
    name: "Kids Adventure",
    description: "Durable and fun eyeglasses designed for active kids",
    price: 59.99,
    images: ["/kids-eyeglasses-colorful.jpg", "/children-glasses-durable.jpg"],
    category: "kids",
    brand: "JuniorVision",
    frameType: "full-rim",
    material: "TR90",
    color: "Blue",
    inStock: true,
    rating: 4.9,
    reviewCount: 423,
    features: ["Flexible Frame", "Impact Resistant", "Adjustable", "Fun Colors"],
  },
]

// Mock addresses data
export const mockAddresses: Address[] = [
  {
    id: "1",
    fullName: "Nguyen Van A",
    phone: "0901234567",
    addressLine1: "123 Nguyen Hue Street",
    city: "Ho Chi Minh City",
    state: "Ho Chi Minh",
    postalCode: "700000",
    country: "Vietnam",
    isDefault: true,
  },
  {
    id: "2",
    fullName: "Nguyen Van A",
    phone: "0901234567",
    addressLine1: "456 Le Loi Avenue",
    addressLine2: "Apartment 5B",
    city: "Hanoi",
    state: "Hanoi",
    postalCode: "100000",
    country: "Vietnam",
    isDefault: false,
  },
]

// Mock orders data
export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    userId: "user-1",
    items: [
      {
        productId: "1",
        product: mockProducts[0],
        quantity: 1,
      },
    ],
    total: 129.99,
    status: "delivered",
    shippingAddress: mockAddresses[0],
    paymentMethod: "Credit Card",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-20T14:45:00Z",
    trackingNumber: "VN123456789",
  },
  {
    id: "ORD-002",
    userId: "user-1",
    items: [
      {
        productId: "2",
        product: mockProducts[1],
        quantity: 2,
      },
    ],
    total: 199.98,
    status: "shipped",
    shippingAddress: mockAddresses[0],
    paymentMethod: "PayPal",
    createdAt: "2024-02-01T09:15:00Z",
    updatedAt: "2024-02-03T11:20:00Z",
    trackingNumber: "VN987654321",
  },
  {
    id: "ORD-003",
    userId: "user-1",
    items: [
      {
        productId: "3",
        product: mockProducts[2],
        quantity: 1,
      },
    ],
    total: 89.99,
    status: "processing",
    shippingAddress: mockAddresses[1],
    paymentMethod: "Credit Card",
    createdAt: "2024-02-10T16:00:00Z",
    updatedAt: "2024-02-10T16:00:00Z",
  },
]
